library(jsonlite)
library(e1071)
library(data.table)
load("model_svm.RData")
#* @post /predict
predict.class=function(profit,jenis_usaha,fisik_usaha,tenor,income,expense,tanggungan,jenis_kelamin,installment,proposed_loan,loan.ratio,score_gt,usia,anggotakeluargabekerja,anggotakeluargabelumbekerja,anggotakeluargabelumbekerja2,izinusaha,jarak,jumlahkamar,jumlahkaryawan,total_aset,jumlahkendaraanpribadi,lamausaha,pembukuanusaha,pendapatansumberlain,grade.pendidikan,statusnikah,statusrumah,tipetempatkerja,oer){
  jenis_usaha=factor(jenis_usaha,level=c("culinary","fashion","other","perdagangan","properti","service"))
  fisik_usaha=factor(fisik_usaha,levels=c("1","2"))
  tanggungan=factor(tanggungan,levels=c("tidak ada", "1-2 orang", "3 oramg atau lebih"))
  jenis_kelamin=factor(jenis_kelamin,levels=c("Pria","Wanita"))
  anggotakeluargabekerja=factor(anggotakeluargabekerja,levels=c("0","1","2","3","4"))
  anggotakeluargabelumbekerja=factor(anggotakeluargabelumbekerja,levels=c("0","1","2"))
  anggotakeluargabelumbekerja2=factor(anggotakeluargabelumbekerja2,levels=c("0","1","2","3","5+"))
  izinusaha=factor(izinusaha,levels=c("tidak ada", "ada"))
  jarak=factor(jarak,levels=c("<1km",">10km","1km – 5 km","5km – 10 km"))
  jumlahkamar=factor(jumlahkamar,levels=c("1","2","3","4","5","5+"))
  jumlahkaryawan=factor(jumlahkaryawan,levels=c("0","1","2","3","5+"))
  jumlahkendaraanpribadi=factor(jumlahkendaraanpribadi,levels=c("0","1","2","3","3+"))
  lamausaha=factor(lamausaha,levels=c(">5 tahun","1 tahun","2 tahun","3 tahun","4 tahun","6 bulan"))
  pembukuanusaha=factor(pembukuanusaha,levels=c("Ada","Tidak Ada"))
  pendapatansumberlain=factor(pendapatansumberlain,levels=c("1","2","3","tidak ada"))
  grade.pendidikan=factor(grade.pendidikan,levels=c("Diploma (D1-D3)","SMA/SMK atau di bawahnya","Strata 1 (S1) atau di atasnya"))
  statusnikah=factor(statusnikah,levels=c("Cerai","Kawin","Tidak Kawin"))
  statusrumah=factor(statusrumah,levels=c("Kontrak / sewa / kost","Milik keluarga","Milik sendiri" ))
  tipetempatkerja=factor(tipetempatkerja,levels=c("Dari Rumah (Milik Sendiri)","Dari Rumah (Sewa)","Gendongan","Gerobakan (Milik Sendiri)","Gerobakan (Sewa)","Lahan/Tembak Sewa","Toko/Rumah Produksi (Milik Sendiri)","Toko/Rumah Produksi (Sewa)","Warung (Milik Sendiri)","Warung (Sewa)"))
  data=data.table(profit=profit,jenis_usaha=jenis_usaha,fisik_usaha=fisik_usaha,tenor=tenor,income=income,expense=expense,tanggungan=tanggungan,jenis_kelamin=jenis_kelamin,installment=installment,proposed_loan=proposed_loan,loan.ratio=loan.ratio,score_gt=score_gt,usia=usia,anggotakeluargabekerja=anggotakeluargabekerja,anggotakeluargabelumbekerja=anggotakeluargabelumbekerja,anggotakeluargabelumbekerja2=anggotakeluargabelumbekerja2,izinusaha=izinusaha,jarak=jarak,jumlahkamar=jumlahkamar,jumlahkaryawan=jumlahkaryawan,total_aset=total_aset,jumlahkendaraanpribadi=jumlahkendaraanpribadi,lamausaha=lamausaha,pembukuanusaha=pembukuanusaha,pendapatansumberlain=pendapatansumberlain,grade.pendidikan=grade.pendidikan,statusnikah=statusnikah,statusrumah=statusrumah,tipetempatkerja=tipetempatkerja,oer=oer)
  prediksi=predict(model.svm,data)
  prediksi=ifelse(prediksi==1,"bermasalah","tidak bermasalah")
  return(list(prediksi=prediksi))
}

